/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("create.text.adventure.java.java-application-conventions")
}

dependencies {
    implementation("org.apache.commons:commons-text")
    implementation(project(":engine"))
}

application {
    // Define the main class for the application.
    mainClass.set("com.github.progdojo.adventure.app.App")
}
